import RPi.GPIO as GPIO
from time import sleep
button = Button(13)
red = LED(18)
amber = LED(8)
green = LED(11)
while True:
    button.wait_for_press()
    red.on()
    button.wait_for_release()
    red.off()
    sleep(2)
    button.wait_for_press()
    amber.on()
    button.wait_for_release()
    amber.off()
    sleep(2)
    button.wait_for_press()
    green.on()
    button.wait_for_release()
    green.off()
    sleep(2)
